### PR TITLE
Prepare version 3 release for Nanopore analysis

### PR DESCRIPTION
**Pull request by peterk87**
This PR is to prepare a v3 release of the workflow adding a Nanopore analysis subworkflow.

The workflow's name has been changed from `nf-iav-illumina` to `nf-flu` and the official repo for `nf-flu` will be [CFIA-NCFAD/nf-flu](https://github.com/CFIA-NCFAD/nf-flu/) going forward.

* Added back `bin/fastq_dir_to_samplesheet.py` for Illumina `--input` samplesheet creation from Illumina FASTQ reads directory
* Fixed [issue #12](https://github.com/peterk87/nf-flu/issues/12). Nanopore sample sheet can specify a mix of single FASTQ files and/or directories containing FASTQ files. Different reads with the same sample name will be merged prior to analysis. FASTQs can be GZIP compressed and have the extensions: `.fastq`, `.fq`, `.fastq.gz`, `.fq.gz`. Updated CI tests to test for this flexible sample sheet handling.
* Switched to GitHub YAML form for bug report template from Markdown template.
* CI tests now output `results/pipeline_info/` and `.nextflow.log` as artifacts for easier debugging of issues.

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [X] Usage Documentation in `docs/usage.md` is updated.
- [X] Output Documentation in `docs/output.md` is updated.
- [X] `CHANGELOG.md` is updated.
- [X] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by nhhaidee** [comment]
@peterk87 I found some bugs from initial test

- Tag of process  `VCF_FILTER_FRAMESHIFT` display incorrectly `NF_FLU:NANOPORE:VCF_FILTER_FRAMESHIFT (ERR6359502|5_NP|null)`. It is caused by  https://github.com/peterk87/nf-flu/blob/d94de883b22956a92dc066598e11a4a275633bd3/modules/local/vcf_filter_frameshift.nf#L2
It should be `$ref_id`
- In `publish_dir/variants` and `publish_dir/reference_sequences`, there is a strange folder name `[:]`
- In MultiQC Report, there is sample name `ERR6359501.Segment_1_PB2.MH201221.no_frameshifts`

**Comment by peterk87** [comment]
> @peterk87 I found some bugs from initial test
> 
>     * Tag of process  `VCF_FILTER_FRAMESHIFT` display incorrectly `NF_FLU:NANOPORE:VCF_FILTER_FRAMESHIFT (ERR6359502|5_NP|null)`. It is caused by  https://github.com/peterk87/nf-flu/blob/d94de883b22956a92dc066598e11a4a275633bd3/modules/local/vcf_filter_frameshift.nf#L2
>       
>       It should be `$ref_id`
> 
>     * In `publish_dir/variants` and `publish_dir/reference_sequences`, there is a strange folder name `[:]`
> 
>     * In MultiQC Report, there is sample name `ERR6359501.Segment_1_PB2.MH201221.no_frameshifts`

Thanks @nhhaidee ! All of these should be fixed in 19698ba

**Comment by nhhaidee** [comment]
@peterk87 The changes look very good to me and tests passed at my end as well, I think you can release it

**Comment by peterk87** [comment]
Thanks @nhhaidee ! I've made a new release at https://github.com/CFIA-NCFAD/nf-flu/releases/tag/3.1.0

**Pull request merged**
